/**
 * Image paths for every animation of the shark (the player character).
 * Each entry is one animation: an array of frame paths that are played in order.
 */
const CHARACTER_IMAGES = {
  swimming: [
    'graphics/1.Sharkie/3.Swim/1.png',
    'graphics/1.Sharkie/3.Swim/2.png',
    'graphics/1.Sharkie/3.Swim/3.png',
    'graphics/1.Sharkie/3.Swim/4.png',
    'graphics/1.Sharkie/3.Swim/5.png',
    'graphics/1.Sharkie/3.Swim/6.png',
  ],

  idle: [
    'graphics/1.Sharkie/1.IDLE/1.png',
    'graphics/1.Sharkie/1.IDLE/2.png',
    'graphics/1.Sharkie/1.IDLE/3.png',
    'graphics/1.Sharkie/1.IDLE/4.png',
    'graphics/1.Sharkie/1.IDLE/5.png',
    'graphics/1.Sharkie/1.IDLE/6.png',
    'graphics/1.Sharkie/1.IDLE/7.png',
    'graphics/1.Sharkie/1.IDLE/8.png',
    'graphics/1.Sharkie/1.IDLE/9.png',
    'graphics/1.Sharkie/1.IDLE/10.png',
    'graphics/1.Sharkie/1.IDLE/11.png',
    'graphics/1.Sharkie/1.IDLE/12.png',
    'graphics/1.Sharkie/1.IDLE/13.png',
    'graphics/1.Sharkie/1.IDLE/14.png',
    'graphics/1.Sharkie/1.IDLE/15.png',
    'graphics/1.Sharkie/1.IDLE/16.png',
    'graphics/1.Sharkie/1.IDLE/17.png',
    'graphics/1.Sharkie/1.IDLE/18.png',
  ],

  longIdle: [
    'graphics/1.Sharkie/2.Long_IDLE/i1.png',
    'graphics/1.Sharkie/2.Long_IDLE/I2.png',
    'graphics/1.Sharkie/2.Long_IDLE/I3.png',
    'graphics/1.Sharkie/2.Long_IDLE/I4.png',
    'graphics/1.Sharkie/2.Long_IDLE/I5.png',
    'graphics/1.Sharkie/2.Long_IDLE/I6.png',
    'graphics/1.Sharkie/2.Long_IDLE/I7.png',
    'graphics/1.Sharkie/2.Long_IDLE/I8.png',
    'graphics/1.Sharkie/2.Long_IDLE/I9.png',
    'graphics/1.Sharkie/2.Long_IDLE/I10.png',
    'graphics/1.Sharkie/2.Long_IDLE/I11.png',
    'graphics/1.Sharkie/2.Long_IDLE/I12.png',
    'graphics/1.Sharkie/2.Long_IDLE/I13.png',
    'graphics/1.Sharkie/2.Long_IDLE/I14.png',
    'graphics/1.Sharkie/2.Long_IDLE/I11.png',
    'graphics/1.Sharkie/2.Long_IDLE/I12.png',
    'graphics/1.Sharkie/2.Long_IDLE/I13.png',
    'graphics/1.Sharkie/2.Long_IDLE/I11.png',
    'graphics/1.Sharkie/2.Long_IDLE/I12.png',
    'graphics/1.Sharkie/2.Long_IDLE/I13.png',
    'graphics/1.Sharkie/2.Long_IDLE/I11.png',
    'graphics/1.Sharkie/2.Long_IDLE/I12.png',
    'graphics/1.Sharkie/2.Long_IDLE/I13.png',
    'graphics/1.Sharkie/2.Long_IDLE/I11.png',
    'graphics/1.Sharkie/2.Long_IDLE/I12.png',
    'graphics/1.Sharkie/2.Long_IDLE/I13.png',
    'graphics/1.Sharkie/2.Long_IDLE/I11.png',
    'graphics/1.Sharkie/2.Long_IDLE/I12.png',
    'graphics/1.Sharkie/2.Long_IDLE/I13.png',
    'graphics/1.Sharkie/2.Long_IDLE/I11.png',
    'graphics/1.Sharkie/2.Long_IDLE/I12.png',
    'graphics/1.Sharkie/2.Long_IDLE/I13.png',
    'graphics/1.Sharkie/2.Long_IDLE/I11.png',
    'graphics/1.Sharkie/2.Long_IDLE/I12.png',
    'graphics/1.Sharkie/2.Long_IDLE/I13.png',
  ],

  tailAttack: [
    'graphics/1.Sharkie/4.Attack/Fin slap/1.png',
    'graphics/1.Sharkie/4.Attack/Fin slap/2.png',
    'graphics/1.Sharkie/4.Attack/Fin slap/3.png',
    'graphics/1.Sharkie/4.Attack/Fin slap/4.png',
    'graphics/1.Sharkie/4.Attack/Fin slap/5.png',
    'graphics/1.Sharkie/4.Attack/Fin slap/6.png',
    'graphics/1.Sharkie/4.Attack/Fin slap/7.png',
    'graphics/1.Sharkie/4.Attack/Fin slap/8.png',
  ],

  bubble: [
    'graphics/1.Sharkie/4.Attack/Bubble trap/op1 (with bubble formation)/1.png',
    'graphics/1.Sharkie/4.Attack/Bubble trap/op1 (with bubble formation)/2.png',
    'graphics/1.Sharkie/4.Attack/Bubble trap/op1 (with bubble formation)/3.png',
    'graphics/1.Sharkie/4.Attack/Bubble trap/op1 (with bubble formation)/4.png',
    'graphics/1.Sharkie/4.Attack/Bubble trap/op1 (with bubble formation)/5.png',
    'graphics/1.Sharkie/4.Attack/Bubble trap/op1 (with bubble formation)/6.png',
    'graphics/1.Sharkie/4.Attack/Bubble trap/op1 (with bubble formation)/7.png',
    'graphics/1.Sharkie/4.Attack/Bubble trap/op1 (with bubble formation)/8.png',
  ],

  poisonBubble: [
    'graphics/1.Sharkie/4.Attack/Bubble trap/For Whale/1.png',
    'graphics/1.Sharkie/4.Attack/Bubble trap/For Whale/2.png',
    'graphics/1.Sharkie/4.Attack/Bubble trap/For Whale/3.png',
    'graphics/1.Sharkie/4.Attack/Bubble trap/For Whale/4.png',
    'graphics/1.Sharkie/4.Attack/Bubble trap/For Whale/5.png',
    'graphics/1.Sharkie/4.Attack/Bubble trap/For Whale/6.png',
    'graphics/1.Sharkie/4.Attack/Bubble trap/For Whale/7.png',
    'graphics/1.Sharkie/4.Attack/Bubble trap/For Whale/8.png',
  ],

  hurtPoison: [
    'graphics/1.Sharkie/5.Hurt/1.Poisoned/1.png',
    'graphics/1.Sharkie/5.Hurt/1.Poisoned/2.png',
    'graphics/1.Sharkie/5.Hurt/1.Poisoned/3.png',
    'graphics/1.Sharkie/5.Hurt/1.Poisoned/4.png',
    'graphics/1.Sharkie/5.Hurt/1.Poisoned/5.png',
  ],

  hurtElectric: [
    'graphics/1.Sharkie/5.Hurt/2.Electric shock/1.png',
    'graphics/1.Sharkie/5.Hurt/2.Electric shock/2.png',
    'graphics/1.Sharkie/5.Hurt/2.Electric shock/3.png',
  ],

  deadPoison: [
    'graphics/1.Sharkie/6.dead/1.Poisoned/1.png',
    'graphics/1.Sharkie/6.dead/1.Poisoned/2.png',
    'graphics/1.Sharkie/6.dead/1.Poisoned/3.png',
    'graphics/1.Sharkie/6.dead/1.Poisoned/4.png',
    'graphics/1.Sharkie/6.dead/1.Poisoned/5.png',
    'graphics/1.Sharkie/6.dead/1.Poisoned/6.png',
    'graphics/1.Sharkie/6.dead/1.Poisoned/7.png',
    'graphics/1.Sharkie/6.dead/1.Poisoned/8.png',
    'graphics/1.Sharkie/6.dead/1.Poisoned/9.png',
    'graphics/1.Sharkie/6.dead/1.Poisoned/10.png',
    'graphics/1.Sharkie/6.dead/1.Poisoned/11.png',
    'graphics/1.Sharkie/6.dead/1.Poisoned/12.png',
  ],

  deadElectric: [
    'graphics/1.Sharkie/6.dead/2.Electro_shock/1.png',
    'graphics/1.Sharkie/6.dead/2.Electro_shock/2.png',
    'graphics/1.Sharkie/6.dead/2.Electro_shock/3.png',
    'graphics/1.Sharkie/6.dead/2.Electro_shock/4.png',
    'graphics/1.Sharkie/6.dead/2.Electro_shock/5.png',
    'graphics/1.Sharkie/6.dead/2.Electro_shock/6.png',
    'graphics/1.Sharkie/6.dead/2.Electro_shock/7.png',
    'graphics/1.Sharkie/6.dead/2.Electro_shock/8.png',
    'graphics/1.Sharkie/6.dead/2.Electro_shock/9.png',
    'graphics/1.Sharkie/6.dead/2.Electro_shock/10.png',
  ],
};
